"""
Generate golden_vectors.json from the Python reference engine.

The Swift port must reproduce every vector. Re-run this whenever pace_engine.py changes
and commit both files together:

    python3 make_golden_vectors.py

Vectors use canonical field names and numeric seconds only. Alias handling and
"mm:ss.s" string parsing are Python conveniences; the Swift port takes typed input from
the OCR/confirmation layer, so those paths are covered by the separate `parsing` block.
"""

from __future__ import annotations

import json
from dataclasses import asdict, replace
from datetime import date, timedelta

import pace_engine as pe

AS_OF = date(2026, 9, 17)


def day(n: int) -> str:
    return (AS_OF - timedelta(days=n)).isoformat()


def coherent_history(s2k: float = 105.0) -> list[dict]:
    """Every session generated by the forward model, so all tiers agree on S2k."""
    rows = []
    plan = [("UT2", 16000, 19), ("UT2", 14000, 20), ("UT1", 12000, 22),
            ("AT", 8000, 26), ("UT2", 18000, 18)]
    for week in range(4):
        for offset, (tag, dist, rate) in enumerate(plan):
            split = round(pe._pace_for(tag, dist, s2k), 1)
            rows.append({"id": f"w{week}-{offset}", "date": day(week * 7 + offset),
                         "distance_m": dist, "split_s": split,
                         "time_s": round(split * dist / 500.0, 1),
                         "stroke_rate": rate, "tag": tag})
    tr = pe._pace_for("TR", 6000, s2k)
    rows.append({"id": "6k-tr", "date": day(9), "distance_m": 6000,
                 "time_s": round(tr * 6000 / 500.0, 1), "stroke_rate": 30, "tag": "TR"})
    return rows


def ut2_rows(n: int, rpe=None, distance=16000, split=127.0) -> list[dict]:
    rows = [{"id": f"u{i}", "date": day(i), "distance_m": distance, "split_s": split,
             "stroke_rate": 19, "tag": "UT2"} for i in range(1, n + 1)]
    if rpe is not None:
        for r in rows:
            r["rpe"] = rpe
    return rows


def with_weights(rows: list[dict], start_kg: float, end_kg: float) -> list[dict]:
    out = [dict(r) for r in rows]
    for r in out:
        days_ago = (AS_OF - pe.parse_date(r["date"])).days
        r["bodyweight_kg"] = round(end_kg + (start_kg - end_kg) * days_ago / 30.0, 3)
    return out


def tired(rows: list[dict]) -> list[dict]:
    out = [dict(r) for r in rows]
    for r in out:
        if r["tag"] == "UT2" and (AS_OF - pe.parse_date(r["date"])).days <= 7:
            r["rpe"] = 5.5
    return out


coherent = coherent_history()

CASES: list[dict] = [
    # --- Core model ------------------------------------------------------------------
    {"name": "coherent_athlete_2k", "history": coherent, "target": 2000},
    {"name": "coherent_athlete_5k", "history": coherent, "target": 5000},
    {"name": "coherent_athlete_6k", "history": coherent, "target": 6000},
    {"name": "single_ut2_15k", "target": 2000,
     "history": [{"id": "u", "date": day(2), "distance_m": 15000, "split_s": 126.9,
                  "stroke_rate": 19, "tag": "UT2"}]},
    {"name": "single_an_2k_test", "target": 2000,
     "history": [{"id": "t", "date": day(3), "distance_m": 2000, "time_s": 420.0,
                  "stroke_rate": 34, "tag": "AN"}]},
    {"name": "ut1_only", "target": 2000,
     "history": [{"id": f"a{i}", "date": day(i), "distance_m": 12000,
                  "split_s": round(pe._pace_for("UT1", 12000, 105.0), 1),
                  "stroke_rate": 22, "tag": "UT1"} for i in range(1, 8)]},
    {"name": "mistagged_6k_tier_disagreement", "target": 2000,
     "history": [r for r in coherent if r["id"] != "6k-tr"] + [
         {"id": "6k-bad", "date": day(9), "distance_m": 6000, "time_s": 1260.0,
          "stroke_rate": 30, "tag": "TR"}]},

    # --- Intervals ---------------------------------------------------------------------
    {"name": "intervals_undeclared", "target": 2000,
     "history": [{"id": "8x500", "date": day(4), "distance_m": 4000, "split_s": 96.0,
                  "stroke_rate": 34, "tag": "AN"}]},
    {"name": "intervals_declared", "target": 2000,
     "history": [{"id": "8x500", "date": day(4), "distance_m": 4000,
                  "rep_distance_m": 500, "split_s": 96.0, "stroke_rate": 34,
                  "tag": "AN"}]},

    # --- Edge cases ----------------------------------------------------------------------
    {"name": "empty_history", "history": [], "target": 2000},
    {"name": "zero_target", "history": coherent, "target": 0},
    {"name": "negative_target", "history": coherent, "target": -2000},
    {"name": "zero_distance_session", "target": 2000,
     "history": [{"id": "z", "date": AS_OF.isoformat(), "distance_m": 0,
                  "time_s": 600.0, "tag": "UT2"}]},
    {"name": "stale_history_only", "target": 2000,
     "history": [{"id": "old", "date": day(120), "distance_m": 2000, "time_s": 420.0,
                  "tag": "AN"}]},
    {"name": "future_session_ignored", "target": 2000,
     "history": coherent + [{"id": "tomorrow",
                             "date": (AS_OF + timedelta(days=1)).isoformat(),
                             "distance_m": 2000, "time_s": 360.0, "tag": "AN"}]},
    {"name": "world_record_clamp", "target": 2000,
     "history": [{"id": "typo", "date": day(1), "distance_m": 2000, "split_s": 60.0,
                  "stroke_rate": 34, "tag": "AN"}]},
    {"name": "split_time_disagreement", "target": 2000,
     "history": [{"id": "d", "date": day(1), "distance_m": 10000, "time_s": 2600.0,
                  "split_s": 118.0, "stroke_rate": 20, "tag": "UT2"}]},
    {"name": "stroke_rate_mismatch", "target": 2000,
     "history": [{"id": "odd", "date": day(1), "distance_m": 10000, "split_s": 125.0,
                  "stroke_rate": 36, "tag": "UT2"}]},
    {"name": "duplicate_ids", "target": 2000,
     "history": coherent + [dict(coherent[0]), dict(coherent[1])]},

    # --- Perceived effort ----------------------------------------------------------------
    {"name": "rpe_ut2_mid", "history": ut2_rows(7, rpe=3), "target": 2000},
    {"name": "rpe_ut2_harder", "history": ut2_rows(7, rpe=4), "target": 2000},
    {"name": "rpe_ut2_easier", "history": ut2_rows(7, rpe=2), "target": 2000},
    {"name": "rpe_ut2_contradiction", "history": ut2_rows(7, rpe=9), "target": 2000},
    {"name": "rpe_an_exempt", "target": 2000,
     "history": [{"id": "t", "date": day(2), "distance_m": 2000, "time_s": 420.0,
                  "tag": "AN", "rpe": 8}]},
    {"name": "rpe_sparse_coverage", "target": 2000,
     "history": [dict(r, rpe=5.0) if r["id"] == "u1" else r for r in ut2_rows(19)]},
    {"name": "rpe_fatigue", "history": tired(coherent), "target": 2000},
    {"name": "rpe_capped_aggressive_config", "target": 2000,
     "config_overrides": {"rpe_sensitivity": 10.0},
     "history": [{"id": "c", "date": day(1), "distance_m": 16000, "split_s": 127.0,
                  "tag": "UT2", "rpe": 5}]},

    # --- Demographics and weight ---------------------------------------------------------
    {"name": "profile_does_not_change_prediction", "history": coherent, "target": 2000,
     "athlete": {"age": 68, "sex": "female", "weight_kg": 55}},
    {"name": "interpretation_weight_and_age", "history": coherent, "target": 2000,
     "athlete": {"age": 55, "sex": "male", "weight_kg": 80}},
    {"name": "weight_trend_off_by_default", "target": 2000,
     "history": with_weights(coherent, 80.0, 74.0)},
    {"name": "weight_trend_enabled_loss", "target": 2000,
     "config_overrides": {"weight_trend_sensitivity": 1.0},
     "history": with_weights(coherent, 80.0, 74.0)},
    {"name": "weight_trend_enabled_gain", "target": 2000,
     "config_overrides": {"weight_trend_sensitivity": 1.0},
     "history": with_weights(coherent, 74.0, 80.0)},

    # --- Cold start ----------------------------------------------------------------------
    {"name": "prior_male_reference", "history": [], "target": 2000,
     "athlete": {"age": 27, "sex": "male", "weight_kg": 82}},
    {"name": "prior_female_reference", "history": [], "target": 2000,
     "athlete": {"age": 27, "sex": "female", "weight_kg": 68}},
    {"name": "prior_nonbinary_only", "history": [], "target": 2000,
     "athlete": {"sex": "nonbinary"}},
    {"name": "prior_older_heavier_5k", "history": [], "target": 5000,
     "athlete": {"age": 55, "sex": "male", "weight_kg": 100}},
    {"name": "prior_not_used_when_history_is_stale", "target": 2000,
     "athlete": {"sex": "male", "age": 30},
     "history": [{"id": "old", "date": day(45), "distance_m": 2000, "time_s": 390.0,
                  "tag": "AN"}]},
    {"name": "prior_implausible_profile_dropped", "history": [], "target": 2000,
     "athlete": {"age": 400, "weight_kg": -3}},
]

# Fields the Swift port must match. Numbers compare within tolerance; flags compare as a
# set; strings exactly. Warnings and recommendation TEXT are deliberately excluded —
# the app owns its copy, and the flags carry the meaning.
NUMERIC_COMPONENTS = ("anchor_split", "paul_adjustment", "intensity_offset",
                      "rpe_correction", "two_k_equivalent", "projection_to_target",
                      "weight_trend_correction", "volume_modifier", "clamp_adjustment",
                      "population_2k_seconds")


def expected_view(result: dict) -> dict:
    anchor = result.get("anchor")
    interp = result.get("interpretation") or {}
    wa, ag = interp.get("weight_adjusted"), interp.get("age_graded")
    return {
        "predicted_split_seconds": result["predicted_split_seconds"],
        "predicted_total_time_seconds": result["predicted_total_time_seconds"],
        "predicted_split_formatted": result["predicted_split_formatted"],
        "predicted_total_time_formatted": result["predicted_total_time_formatted"],
        "predicted_split_range_seconds": result["predicted_split_range_seconds"],
        "predicted_total_time_range_seconds": result["predicted_total_time_range_seconds"],
        "confidence_score": result["confidence_score"],
        "confidence_numeric": result["confidence_numeric"],
        "anchor_tier": anchor["tier"] if anchor else None,
        "anchor_method": anchor["method"] if anchor else None,
        "anchor_session_ids": anchor["session_ids"] if anchor else None,
        "components": {k: v for k, v in (result.get("components") or {}).items()
                       if k in NUMERIC_COMPONENTS and v is not None},
        "load_trimp_lite": result["load"]["trimp_lite"],
        "load_modifier_seconds": result["load"]["modifier_seconds"],
        "spread_seconds": result["diagnostics"]["spread_seconds"],
        "two_k_equivalent_by_tier": result["diagnostics"]["two_k_equivalent_by_tier"],
        "weight_adjusted_total_seconds": wa["total_time_seconds"] if wa else None,
        "age_graded_total_seconds": ag["total_time_seconds"] if ag else None,
        "flags": sorted(set(result["flags"])),
    }


def build() -> dict:
    vectors = []
    for case in CASES:
        config = replace(pe.DEFAULT_CONFIG, **case.get("config_overrides", {}))
        result = pe.predict_test_piece(case["history"], case["target"], AS_OF, config,
                                       athlete=case.get("athlete"))
        json.dumps(result)  # must be serialisable
        vectors.append({
            "name": case["name"],
            "as_of": AS_OF.isoformat(),
            "target_distance_m": case["target"],
            "config_overrides": case.get("config_overrides", {}),
            "athlete": case.get("athlete"),
            "history": case["history"],
            "expected": expected_view(result),
        })

    parsing = {
        "format_seconds": [{"in": v, "out": pe.format_seconds(v)}
                           for v in (0.4, 59.96, 105.0, 419.96, 421.2, 3599.99, 5025.6)],
        "weight_adjustment_factor": [{"weight_kg": w,
                                      "out": round(pe.weight_adjustment_factor(w), 10)}
                                     for w in (55.0, 68.0, 80.0, 100.0, 122.47)],
        "age_performance_factor": [{"age": a,
                                    "out": round(pe.age_performance_factor(a), 10)}
                                   for a in (12, 16, 18, 22, 27, 30, 35, 40, 50, 55, 70,
                                             85)],
        "normalise_rpe": [{"in": v, "out": pe._normalise_rpe(v)}
                          for v in (0, 3, 7.5, 10, 10.5, 11, 15, 20, 20.5, -1)],
    }

    return {
        "schema_version": pe.SCHEMA_VERSION,
        "generated_from": "pace_engine.py (Python reference implementation)",
        "tolerance": {
            "seconds": 0.02,
            "note": "Python rounds half-to-even, Swift's .rounded() half-away-from-zero. "
                    "Compare numbers within 0.02, not for exact equality.",
        },
        "config": {k: v for k, v in asdict(pe.DEFAULT_CONFIG).items()},
        "tiers": {k: asdict(v) for k, v in pe.TIERS.items()},
        "cases": vectors,
        "parsing": parsing,
    }


if __name__ == "__main__":
    data = build()
    with open("golden_vectors.json", "w") as fh:
        json.dump(data, fh, indent=2)
    print(f"wrote golden_vectors.json: {len(data['cases'])} cases, "
          f"{sum(len(v) for v in data['parsing'].values())} parsing checks")
