-- The club directory (decision 25): every UK university and college boat club, and the UK's
-- established membership clubs (Leander, Thames, London RC, Molesey…). Run after
-- docs/migrations/2026-09-30-clubs.sql. Safe to run again: existing clubs are left alone.
--
-- Sources (September 2026): Wikipedia "University rowing in the United Kingdom" (university
-- and college boat clubs, including those not affiliated to British Rowing) and "List of
-- rowing clubs" (UK clubs, less university, college and school clubs), plus Upper Thames,
-- Quintin, Poplar Blackwall & District, Cardiff City, Belfast RC, Lagan Scullers and Commercial
-- BC. Where two clubs share a name, the town is added in brackets. All start open to join and
-- with no owner; an owner is made in the SQL editor.

insert into clubs (name, location, focus, join_policy)
select v.name, v.location, v.focus, 'open'
from (values
  ('AB Severn Rowing Club', 'Tewkesbury', 'All rowing'),
  ('Aberdeen Boat Club', 'Aberdeen', 'All rowing'),
  ('Aberdeen University Boat Club', 'Aberdeen', 'University crew'),
  ('Aberystwyth University Boat Club', 'Aberystwyth', 'University crew'),
  ('Abingdon Rowing Club', 'Abingdon', 'All rowing'),
  ('Agecroft Rowing Club', 'Salford', 'All rowing'),
  ('Anglia Ruskin Boat Club', 'Cambridge', 'University crew'),
  ('Aston University Rowing Club', 'Birmingham', 'University crew'),
  ('Auriol Kensington Rowing Club', 'London', 'All rowing'),
  ('Avon County Rowing Club', 'Bristol', 'All rowing'),
  ('Balliol College Boat Club', 'Oxford', 'University crew'),
  ('Bangor University Rowing Club', 'Bangor', 'University crew'),
  ('Bann Rowing Club', 'Coleraine', 'All rowing'),
  ('Barn Elms Rowing Club', 'London', 'All rowing'),
  ('Barnes Bridge Ladies Rowing Club', 'London', 'All rowing'),
  ('Bath Spa University Boat Club', 'Bath', 'University crew'),
  ('Bath University Boat Club', 'Bath', 'University crew'),
  ('Bedford Rowing Club', 'Bedford', 'All rowing'),
  ('Belfast Rowing Club', 'Belfast', 'All rowing'),
  ('Berwick Amateur Rowing Club', 'Berwick-upon-Tweed', 'All rowing'),
  ('Bewdley Rowing Club', 'Bewdley', 'All rowing'),
  ('Bewl Bridge Rowing Club', 'Lamberhurst', 'All rowing'),
  ('Birmingham City University Boat Club', 'Birmingham', 'University crew'),
  ('Birmingham Rowing Club', 'Birmingham', 'All rowing'),
  ('Bournemouth Rowing Club', 'Bournemouth', 'All rowing'),
  ('Bournemouth University Boat Club', 'Bournemouth', 'University crew'),
  ('Bradford Amateur Rowing Club', 'Saltaire', 'All rowing'),
  ('Brasenose College Boat Club', 'Oxford', 'University crew'),
  ('Bristol Ariel Rowing Club', 'Bristol', 'All rowing'),
  ('Broxbourne Rowing Club', 'Broxbourne', 'All rowing'),
  ('Brunel University Rowing Club', 'London', 'University crew'),
  ('Burton Leander Rowing Club', 'Burton upon Trent', 'All rowing'),
  ('Burway Rowing Club', 'Laleham', 'All rowing'),
  ('Butler College Boat Club', 'Durham', 'University crew'),
  ('Caius Boat Club', 'Cambridge', 'University crew'),
  ('Cambois Rowing Club', 'Cambois', 'All rowing'),
  ('Cambridge ''99 Rowing Club', 'Cambridge', 'All rowing'),
  ('Cambridge University Boat Club', 'Cambridge', 'University crew'),
  ('Cambridge University Lightweight Rowing Club', 'Cambridge', 'University crew'),
  ('Cambridge University Women''s Boat Club', 'Cambridge', 'University crew'),
  ('Cantabrigian Rowing Club', 'Cambridge', 'All rowing'),
  ('Cardiff City Rowing Club', 'Cardiff', 'All rowing'),
  ('Cardiff University Rowing Club', 'Cardiff', 'University crew'),
  ('Castle Semple Rowing Club', 'Lochwinnoch', 'All rowing'),
  ('Chester University Rowing Club', 'Chester', 'University crew'),
  ('Chester-le-Street Amateur Rowing Club', 'Chester-le-Street', 'All rowing'),
  ('Christ Church Boat Club', 'Oxford', 'University crew'),
  ('Christ''s College Boat Club', 'Cambridge', 'University crew'),
  ('Christchurch Rowing Club', 'Christchurch', 'All rowing'),
  ('Churchill College Boat Club', 'Cambridge', 'University crew'),
  ('City of Bristol Rowing Club', 'Bristol', 'All rowing'),
  ('City of Cambridge Rowing Club', 'Cambridge', 'All rowing'),
  ('City of Oxford Rowing Club', 'Oxford', 'All rowing'),
  ('City of Sheffield Rowing Club', 'Sheffield', 'All rowing'),
  ('Clare Boat Club', 'Cambridge', 'University crew'),
  ('Clare Hall Boat Club', 'Cambridge', 'University crew'),
  ('Clyde Amateur Rowing Club', 'Glasgow', 'All rowing'),
  ('Clydesdale Amateur Rowing Club', 'Glasgow', 'All rowing'),
  ('Collingwood College Boat Club', 'Durham', 'University crew'),
  ('Commercial Boat Club', 'Belfast', 'All rowing'),
  ('Corpus Christi College Boat Club (Cambridge)', 'Cambridge', 'University crew'),
  ('Corpus Christi College Boat Club (Oxford)', 'Oxford', 'University crew'),
  ('Dart Totnes Amateur Rowing Club', 'Totnes', 'All rowing'),
  ('Darwin College Boat Club', 'Cambridge', 'University crew'),
  ('De Montfort University Rowing Club', 'Leicester', 'University crew'),
  ('Derby Rowing Club', 'Derby', 'All rowing'),
  ('Downing College Boat Club', 'Cambridge', 'University crew'),
  ('Dundee University Boat Club', 'Dundee', 'University crew'),
  ('Durham Amateur Rowing Club', 'Durham', 'All rowing'),
  ('Durham University Boat Club', 'Durham', 'University crew'),
  ('Edinburgh University Boat Club', 'Edinburgh', 'University crew'),
  ('Emmanuel Boat Club', 'Cambridge', 'University crew'),
  ('Essex University Rowing Club', 'Colchester', 'University crew'),
  ('Eton Excelsior Rowing Club', 'Windsor', 'All rowing'),
  ('Evesham Rowing Club', 'Evesham', 'All rowing'),
  ('Exeter College Boat Club', 'Oxford', 'University crew'),
  ('Exeter Rowing Club', 'Exeter', 'All rowing'),
  ('Exeter University Boat Club', 'Exeter', 'University crew'),
  ('First and Third Trinity Boat Club', 'Cambridge', 'University crew'),
  ('Fitzwilliam College Boat Club', 'Cambridge', 'University crew'),
  ('Furnivall Sculling Club', 'London', 'All rowing'),
  ('Girton College Boat Club', 'Cambridge', 'University crew'),
  ('Glasgow Rowing Club', 'Glasgow', 'All rowing'),
  ('Glasgow University Boat Club', 'Glasgow', 'University crew'),
  ('Globe Rowing Club', 'London', 'All rowing'),
  ('Gloucester Rowing Club', 'Gloucester', 'All rowing'),
  ('Gloucestershire University Rowing Club', 'Cheltenham', 'University crew'),
  ('Green Templeton Boat Club', 'Oxford', 'University crew'),
  ('Grey College Boat Club', 'Durham', 'University crew'),
  ('Grosvenor Rowing Club', 'Chester', 'All rowing'),
  ('Guildford Rowing Club', 'Guildford', 'All rowing'),
  ('Harper Adams University Rowing Club', 'Newport, Shropshire', 'University crew'),
  ('Hartpury College and University Boat Club', 'Gloucester', 'University crew'),
  ('Hatfield College Boat Club', 'Durham', 'University crew'),
  ('Henley Rowing Club', 'Henley-on-Thames', 'All rowing'),
  ('Hereford Rowing Club', 'Hereford', 'All rowing'),
  ('Heriot Watt University Boat Club', 'Edinburgh', 'University crew'),
  ('Hertford College Boat Club', 'Oxford', 'University crew'),
  ('Hexham Rowing Club', 'Hexham', 'All rowing'),
  ('Hild Bede Boat Club', 'Durham', 'University crew'),
  ('Hinksey Sculling School', 'Oxford', 'All rowing'),
  ('Hollingworth Lake Rowing Club', 'Littleborough', 'All rowing'),
  ('Homerton College Boat Club', 'Cambridge', 'University crew'),
  ('HSBC Rowing Club', 'London', 'All rowing'),
  ('Hughes Hall Boat Club', 'Cambridge', 'University crew'),
  ('Hull University Boat Club', 'Hull', 'University crew'),
  ('Imperial College Boat Club', 'London', 'University crew'),
  ('Imperial College School of Medicine Boat Club', 'London', 'University crew'),
  ('Inverness Rowing Club', 'Inverness', 'All rowing'),
  ('Isle of Ely Rowing Club', 'Ely', 'All rowing'),
  ('Jesus College Boat Club (Cambridge)', 'Cambridge', 'University crew'),
  ('Jesus College Boat Club (Oxford)', 'Oxford', 'University crew'),
  ('John Snow College Boat Club', 'Durham', 'University crew'),
  ('Keble College Boat Club', 'Oxford', 'University crew'),
  ('Keele University Boat Club', 'Keele', 'University crew'),
  ('King''s College Boat Club', 'Cambridge', 'University crew'),
  ('King''s College London Boat Club', 'London', 'University crew'),
  ('Kingston Rowing Club', 'Kingston upon Thames', 'All rowing'),
  ('Kingston Student Rowing Club', 'Kingston upon Thames', 'University crew'),
  ('Lady Margaret Boat Club', 'Cambridge', 'University crew'),
  ('Lady Margaret Hall Boat Club', 'Oxford', 'University crew'),
  ('Lagan Scullers Club', 'Belfast', 'All rowing'),
  ('Lancaster John O''Gaunt Rowing Club', 'Lancaster', 'All rowing'),
  ('Lancaster University Boat Club', 'Lancaster', 'University crew'),
  ('Lea Rowing Club', 'London', 'All rowing'),
  ('Leander Club', 'Henley-on-Thames', 'All rowing'),
  ('Leeds Beckett University Rowing Club', 'Leeds', 'University crew'),
  ('Leeds Rowing Club', 'Leeds', 'All rowing'),
  ('Leeds University Boat Club', 'Leeds', 'University crew'),
  ('Leicester Rowing Club', 'Leicester', 'All rowing'),
  ('Linacre College Boat Club', 'Oxford', 'University crew'),
  ('Lincoln College Boat Club', 'Oxford', 'University crew'),
  ('Lincoln Rowing Centre', 'Lincoln', 'All rowing'),
  ('Liverpool John Moores University Rowing Club', 'Liverpool', 'University crew'),
  ('Liverpool University Boat Club', 'Liverpool', 'University crew'),
  ('Llandaff Rowing Club', 'Cardiff', 'All rowing'),
  ('Loch Lomond Rowing Club', 'Balloch', 'All rowing'),
  ('London Otters Rowing Club', 'London', 'All rowing'),
  ('London Rowing Club', 'London', 'All rowing'),
  ('London School of Economics Boat Club', 'London', 'University crew'),
  ('Loughborough Students Rowing', 'Loughborough', 'University crew'),
  ('Lucy Cavendish College Boat Club', 'Cambridge', 'University crew'),
  ('Magdalen College Boat Club', 'Oxford', 'University crew'),
  ('Magdalene Boat Club', 'Cambridge', 'University crew'),
  ('Maidenhead Rowing Club', 'Maidenhead', 'All rowing'),
  ('Maidstone Invicta Rowing Club', 'Maidstone', 'All rowing'),
  ('Manchester University Boat Club', 'Manchester', 'University crew'),
  ('Mansfield College Boat Club', 'Oxford', 'University crew'),
  ('Marlow Rowing Club', 'Marlow', 'All rowing'),
  ('Medway Towns Rowing Club', 'Rochester', 'All rowing'),
  ('Merton College Boat Club', 'Oxford', 'University crew'),
  ('Minerva Bath Rowing Club', 'Bath', 'All rowing'),
  ('Molesey Boat Club', 'Molesey', 'All rowing'),
  ('Monmouth Rowing Club', 'Monmouth', 'All rowing'),
  ('Mortlake Anglian & Alpha Boat Club', 'London', 'All rowing'),
  ('Murray Edwards College Boat Club', 'Cambridge', 'University crew'),
  ('New College Boat Club', 'Oxford', 'University crew'),
  ('Newark Rowing Club', 'Newark-on-Trent', 'All rowing'),
  ('Newcastle University Boat Club', 'Newcastle upon Tyne', 'University crew'),
  ('Newnham College Boat Club', 'Cambridge', 'University crew'),
  ('Nithsdale Amateur Rowing Club', 'Dumfries', 'All rowing'),
  ('Northumbria University Boat Club', 'Newcastle upon Tyne', 'University crew'),
  ('Northwich Rowing Club', 'Northwich', 'All rowing'),
  ('Norwich Rowing Club', 'Norwich', 'All rowing'),
  ('Nottingham & Union Rowing Club', 'Nottingham', 'All rowing'),
  ('Nottingham Rowing Club', 'Nottingham', 'All rowing'),
  ('Nottingham Trent University Rowing Club', 'Nottingham', 'University crew'),
  ('Nottingham University Boat Club', 'Nottingham', 'University crew'),
  ('Nottinghamshire County Rowing Association', 'Nottingham', 'All rowing'),
  ('Oriel College Boat Club', 'Oxford', 'University crew'),
  ('Osler House Boat Club', 'Oxford', 'University crew'),
  ('Oxford Brookes University Boat Club', 'Oxford', 'University crew'),
  ('Oxford University Boat Club', 'Oxford', 'University crew'),
  ('Oxford University Lightweight Rowing Club', 'Oxford', 'University crew'),
  ('Oxford University Women''s Boat Club', 'Oxford', 'University crew'),
  ('Oxford University Women''s Lightweight Rowing Club', 'Oxford', 'University crew'),
  ('Paignton Amateur Rowing Club', 'Paignton', 'All rowing'),
  ('Pembroke College Boat Club (Cambridge)', 'Cambridge', 'University crew'),
  ('Pembroke College Boat Club (Oxford)', 'Oxford', 'University crew'),
  ('Peterborough City Rowing Club', 'Peterborough', 'All rowing'),
  ('Peterhouse Boat Club', 'Cambridge', 'University crew'),
  ('Poplar Blackwall & District Rowing Club', 'London', 'All rowing'),
  ('Putney Town Rowing Club', 'London', 'All rowing'),
  ('Queen Mary, University of London Boat Club', 'London', 'University crew'),
  ('Queen''s College Boat Club', 'Oxford', 'University crew'),
  ('Queen''s University Belfast Boat Club', 'Belfast', 'University crew'),
  ('Queen''s University Belfast Ladies Boat Club', 'Belfast', 'University crew'),
  ('Queens'' College Boat Club', 'Cambridge', 'University crew'),
  ('Quintin Boat Club', 'London', 'All rowing'),
  ('Reading Rowing Club', 'Reading', 'All rowing'),
  ('Reading University Boat Club', 'Reading', 'University crew'),
  ('Regent''s Park College Boat Club', 'Oxford', 'University crew'),
  ('Rob Roy Boat Club', 'Cambridge', 'All rowing'),
  ('Robert Gordon University Boat Club', 'Aberdeen', 'University crew'),
  ('Robinson College Boat Club', 'Cambridge', 'University crew'),
  ('Roehampton University Boat Club', 'London', 'University crew'),
  ('Ross Rowing Club', 'Ross-on-Wye', 'All rowing'),
  ('Royal Agricultural University Boat Club', 'Cirencester', 'University crew'),
  ('Royal Chester Rowing Club', 'Chester', 'All rowing'),
  ('Royal Free and University College Medical School Boat Club', 'London', 'University crew'),
  ('Royal Holloway, University of London Boat Club', 'London', 'University crew'),
  ('Royal Veterinary College Boat Club', 'London', 'University crew'),
  ('Runcorn Rowing Club', 'Runcorn', 'All rowing'),
  ('Salford University Boat Club', 'Salford', 'University crew'),
  ('Selwyn College Boat Club', 'Cambridge', 'University crew'),
  ('Shanklin Sandown Rowing Club', 'Shanklin', 'All rowing'),
  ('Sheffield Hallam University Rowing Club', 'Sheffield', 'University crew'),
  ('Sheffield University Rowing Club', 'Sheffield', 'University crew'),
  ('Shiplake Vikings Rowing Club', 'Shiplake', 'All rowing'),
  ('Sidney Sussex Boat Club', 'Cambridge', 'University crew'),
  ('Somerville College Boat Club', 'Oxford', 'University crew'),
  ('Sons of the Thames', 'London', 'All rowing'),
  ('South College Boat Club', 'Durham', 'University crew'),
  ('Southampton Solent University Boat Club', 'Southampton', 'University crew'),
  ('Southampton University Boat Club', 'Southampton', 'University crew'),
  ('St Aidan''s College Boat Club', 'Durham', 'University crew'),
  ('St Andrew Boat Club', 'Edinburgh', 'All rowing'),
  ('St Anne''s College Boat Club', 'Oxford', 'University crew'),
  ('St Antony''s College Boat Club', 'Oxford', 'University crew'),
  ('St Bartholomew''s and The Royal London Hospitals'' Boat Club', 'London', 'University crew'),
  ('St Benet’s, Blackfriars’ and Reuben College BC', 'Oxford', 'University crew'),
  ('St Catharine''s College Boat Club', 'Cambridge', 'University crew'),
  ('St Catherine''s College Boat Club', 'Oxford', 'University crew'),
  ('St Chad''s College Boat Club', 'Durham', 'University crew'),
  ('St Cuthbert''s Society Boat Club', 'Durham', 'University crew'),
  ('St Edmund Hall Boat Club', 'Oxford', 'University crew'),
  ('St Edmund''s College Boat Club', 'Cambridge', 'University crew'),
  ('St George''s Hospital Medical School Boat Club', 'London', 'University crew'),
  ('St Hilda''s College Boat Club', 'Oxford', 'University crew'),
  ('St Hugh''s College Boat Club', 'Oxford', 'University crew'),
  ('St Ives Rowing Club', 'St Ives', 'All rowing'),
  ('St John''s College Boat Club (Durham)', 'Durham', 'University crew'),
  ('St John''s College Boat Club (Oxford)', 'Oxford', 'University crew'),
  ('St Mary''s College Boat Club', 'Durham', 'University crew'),
  ('St Neots Rowing Club', 'St Neots', 'All rowing'),
  ('St Peter''s College Boat Club', 'Oxford', 'University crew'),
  ('Staines Boat Club', 'Staines-upon-Thames', 'All rowing'),
  ('Star Club & Bedford Star', 'Bedford', 'All rowing'),
  ('Stephenson College Boat Club', 'Durham', 'University crew'),
  ('Stirling Rowing Club', 'Stirling', 'All rowing'),
  ('Stirling University Boat Club', 'Stirling', 'University crew'),
  ('Stratford-upon-Avon Boat Club', 'Stratford-upon-Avon', 'All rowing'),
  ('Strathclyde Park Rowing Club', 'Motherwell', 'All rowing'),
  ('Strathclyde University Boat Club', 'Glasgow', 'University crew'),
  ('Sudbury Rowing Club', 'Sudbury', 'All rowing'),
  ('Sunderland University Rowing Club', 'Sunderland', 'University crew'),
  ('Swansea University Rowing Club', 'Swansea', 'University crew'),
  ('Talkin Tarn Amateur Rowing Club', 'Brampton', 'All rowing'),
  ('Tees Rowing Club', 'Stockton-on-Tees', 'All rowing'),
  ('Teesside University Rowing Club', 'Middlesbrough', 'University crew'),
  ('Thames Rowing Club', 'London', 'All rowing'),
  ('Thames Tradesmen''s Rowing Club', 'London', 'All rowing'),
  ('Tideway Scullers School', 'London', 'All rowing'),
  ('Trent Rowing Club', 'Nottingham', 'All rowing'),
  ('Trevelyan College Boat Club', 'Durham', 'University crew'),
  ('Trinity College Boat Club', 'Oxford', 'University crew'),
  ('Trinity Hall Boat Club', 'Cambridge', 'University crew'),
  ('Twickenham Rowing Club', 'Twickenham', 'All rowing'),
  ('Tyne Rowing Club', 'Newcastle upon Tyne', 'All rowing'),
  ('Ulster University Rowing Club', 'Coleraine', 'University crew'),
  ('United Hospitals Boat Club', 'London', 'University crew'),
  ('University College Boat Club (Durham)', 'Durham', 'University crew'),
  ('University College Boat Club (Oxford)', 'Oxford', 'University crew'),
  ('University College London Boat Club', 'London', 'University crew'),
  ('University of Birmingham Boat Club', 'Birmingham', 'University crew'),
  ('University of Bradford Rowing Club', 'Bradford', 'University crew'),
  ('University of Bristol Boat Club', 'Bristol', 'University crew'),
  ('University of Derby Rowing Club', 'Derby', 'University crew'),
  ('University of East London Boat Club', 'London', 'University crew'),
  ('University of Hertfordshire Rowing Club', 'Hatfield', 'University crew'),
  ('University of Kent Rowing Club', 'Canterbury', 'University crew'),
  ('University of Leicester Boat Club', 'Leicester', 'University crew'),
  ('University of Lincoln Rowing Club', 'Lincoln', 'University crew'),
  ('University of London Boat Club', 'London', 'University crew'),
  ('University of Northampton Rowing Club', 'Northampton', 'University crew'),
  ('University of Plymouth Rowing Club', 'Plymouth', 'University crew'),
  ('University of Portsmouth Rowing Club', 'Portsmouth', 'University crew'),
  ('University of St Andrews Boat Club', 'St Andrews', 'University crew'),
  ('University of Surrey Boat Club', 'Guildford', 'University crew'),
  ('University of the West of England Boat Club', 'Bristol', 'University crew'),
  ('University of Warwick Boat Club', 'Coventry', 'University crew'),
  ('University of Westminster Boat Club', 'London', 'University crew'),
  ('University of Worcester Rowing Club', 'Worcester', 'University crew'),
  ('University of York Boat Club', 'York', 'University crew'),
  ('Upper Thames Rowing Club', 'Henley-on-Thames', 'All rowing'),
  ('Ustinov Boat Club', 'Durham', 'University crew'),
  ('Van Mildert Boat Club', 'Durham', 'University crew'),
  ('Vesta Rowing Club', 'London', 'All rowing'),
  ('Wadham College Boat Club', 'Oxford', 'University crew'),
  ('Walbrook Rowing Club', 'London', 'All rowing'),
  ('Wallingford Rowing Club', 'Wallingford', 'All rowing'),
  ('Walton Rowing Club', 'Walton-on-Thames', 'All rowing'),
  ('Warrington Rowing Club', 'Warrington', 'All rowing'),
  ('Weybridge Ladies Amateur Rowing Club', 'Weybridge', 'All rowing'),
  ('Weybridge Rowing Club', 'Weybridge', 'All rowing'),
  ('Wolfson College Boat Club (Cambridge)', 'Cambridge', 'University crew'),
  ('Wolfson College Boat Club (Oxford)', 'Oxford', 'University crew'),
  ('Worcester College Boat Club', 'Oxford', 'University crew'),
  ('Worcester College Women''s Boat Club', 'Oxford', 'University crew'),
  ('Worcester Rowing Club', 'Worcester', 'All rowing'),
  ('York City Rowing Club', 'York', 'All rowing'),
  ('York St John University Rowing Club', 'York', 'University crew')
) as v(name, location, focus)
where not exists (select 1 from clubs c where lower(c.name) = lower(v.name));

-- UEA Boat Club was already here (it is the University of East Anglia's club).
update clubs set location = 'Norwich', focus = 'University crew' where lower(name) = 'uea boat club';

-- Placeholder clubs from early testing, removed only while nobody is in them.
delete from clubs c
where c.name in ('UEA novice', 'Durham University BC', 'York St John RC')
  and not exists (select 1 from profiles p where p.club_id = c.id);
